apiVersion: v1
kind: Pod
metadata:
  name: master-1
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/kube-apiserver:v1.8.4
    command:
    - /usr/local/bin/kube-apiserver
    - --insecure-bind-address=0.0.0.0
    - --etcd-servers=http://127.0.0.1:4001
    - --service-cluster-ip-range=172.16.0.0/16
    - --insecure-port=8080
    - --authorization-mode=Node
    - --secure-port=0
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: http
  - name: kube-controller-manager
    image: gcr.io/google_containers/kube-controller-manager:v1.8.4
    command:
    - /usr/local/bin/kube-controller-manager
    - --master=127.0.0.1:8080
    - --cluster-cidr=172.16.0.0/16
    - --leader-elect=false
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    ports:
    - containerPort: 10252
      hostPort: 10252
      name: http
  - name: kube-scheduler
    image: gcr.io/google_containers/kube-scheduler:v1.8.4
    command:
    - /usr/local/bin/kube-scheduler
    - --master=127.0.0.1:8080
    - --leader-elect=false
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    ports:
    - containerPort: 10251
      hostPort: 10251
      name: http
  - name: etcd-container
    image: gcr.io/google_containers/etcd:3.0.17
    command:
    - /usr/local/bin/etcd
    - --name=default
    - --advertise-client-urls=http://127.0.0.1:4001
    - --listen-client-urls=http://0.0.0.0:4001
    - --data-dir=/var/etcd/data
    - --discovery=4f10daaa8d4299d0df09b543cd88faa1
    ports:
    - containerPort: 2380
      hostPort: 2380
      name: serverport
    - containerPort: 4001
      hostPort: 4001
      name: clientport
    volumeMounts:
    - mountPath: /var/etcd
      name: varetcd
  volumes:
  - hostPath:
      path: /var/etcd/data
    name: varetcd